"""Generate the MITgcm ``SIZE.h`` Fortran header for a given grid.

The canonical reference file lives at ``code/SIZE.h`` and is hard-coded for
the historical 128×64×20 layout. To compile at any other resolution we
write a fresh ``SIZE.h`` into a per-resolution ``mods/`` directory and pass
that path to ``genmake2 -mods=...``.

MPI layout choice
-----------------
The current Held-Suarez build uses a single tile in X (``nPx = nSx = 1``,
``sNx = Nlon``) and splits Y across MPI ranks (``nPy = n_mpi``,
``sNy = Nlat / n_mpi``). This keeps the polar Shapiro filter on one rank
and avoids cross-rank halo exchanges in the singular zonal direction. The
generator preserves that choice; only ``sNy`` and ``nPy`` change with
``n_mpi``.

The function raises ``ValueError`` if the requested ``n_mpi`` does not
evenly divide ``Nlat``.
"""

from __future__ import annotations

from pathlib import Path


# Default halo size, matching the canonical ``code/SIZE.h``. Larger Shapiro
# orders would require widening this; the held-suarez build uses
# ``nShapUV = nShapT = 4`` which is comfortably covered by OLx = OLy = 3.
_DEFAULT_HALO: int = 3


def render_size_h(
    *,
    Nlon: int,
    Nlat: int,
    Nr: int,
    n_mpi: int,
    OLx: int = _DEFAULT_HALO,
    OLy: int = _DEFAULT_HALO,
) -> str:
    """Return the text of a ``SIZE.h`` for the given grid + MPI layout.

    Args:
        Nlon:  Number of longitude points (= sNx; one X tile).
        Nlat:  Number of latitude points  (= sNy * nPy).
        Nr:    Number of vertical levels.
        n_mpi: Number of MPI ranks. Must evenly divide ``Nlat``.
        OLx:   X halo width (ghost cells per side).
        OLy:   Y halo width.

    Returns:
        Fortran source for SIZE.h.

    Raises:
        ValueError: If ``Nlat`` is not divisible by ``n_mpi``.
    """
    if Nlat % n_mpi != 0:
        raise ValueError(
            f"Nlat={Nlat} is not divisible by n_mpi={n_mpi}; choose a "
            f"divisor of Nlat for the MPI rank count."
        )
    sNx = int(Nlon)
    sNy = int(Nlat // n_mpi)
    nSx = 1
    nSy = 1
    nPx = 1
    nPy = int(n_mpi)

    return (
        "C     SIZE.h — generated by datagen.mitgcm.held_suarez._size_h.\n"
        f"C     Grid: {Nlon} lon × {Nlat} lat × {Nr} pressure levels.\n"
        f"C     MPI layout: nPy={nPy}, sNy={sNy} (one X tile, sNx=Nlon).\n"
        "C     Editing this file directly will not survive a rebuild — change\n"
        "C     scripts/build.py CLI flags instead.\n"
        "\n"
        "      INTEGER sNx, sNy, OLx, OLy, nSx, nSy, nPx, nPy, Nx, Ny, Nr\n"
        "      PARAMETER (\n"
        f"     &           sNx = {sNx:6d},\n"
        f"     &           sNy = {sNy:6d},\n"
        f"     &           OLx = {OLx:6d},\n"
        f"     &           OLy = {OLy:6d},\n"
        f"     &           nSx = {nSx:6d},\n"
        f"     &           nSy = {nSy:6d},\n"
        f"     &           nPx = {nPx:6d},\n"
        f"     &           nPy = {nPy:6d},\n"
        "     &           Nx  = sNx*nSx*nPx,\n"
        "     &           Ny  = sNy*nSy*nPy,\n"
        f"     &           Nr  = {int(Nr):6d})\n"
        "\n"
        "      INTEGER MAX_OLX\n"
        "      INTEGER MAX_OLY\n"
        "      PARAMETER ( MAX_OLX = OLx,\n"
        "     &            MAX_OLY = OLy )\n"
    )


def write_size_h(
    path: Path,
    *,
    Nlon: int,
    Nlat: int,
    Nr: int,
    n_mpi: int,
) -> None:
    """Write a generated ``SIZE.h`` to ``path``."""
    text = render_size_h(Nlon=Nlon, Nlat=Nlat, Nr=Nr, n_mpi=n_mpi)
    Path(path).write_text(text)
