"""Generate MITgcm Fortran namelist files for the Held-Suarez configuration.

Each public function writes one namelist file to disk. The two-phase execution
strategy (spin-up then data-collection restart) requires slightly different
``data`` namelists; ``write_data`` accepts a ``phase`` argument.

Namelist syntax conventions (Fortran 90):
- Opening ``&NAMELIST_NAME`` with leading space.
- Each parameter on its own line, trailing comma.
- Closing `` /`` with leading space.
- String literals in single quotes, padded to 8 chars for field names.
- Real literals always include a decimal point.
- Arrays: ``N*value`` for N identical values, or comma-separated.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from datagen.mitgcm._constants import (
    CP,
    KAPPA,
    P0,
    R_DRY,
    R_EARTH,
)
from datagen.mitgcm._held_suarez import reference_temperature_profile


def _fmt_real(v: float) -> str:
    """Format a float for a Fortran namelist (always has decimal point)."""
    return f"{v:.8g}"


def _pressure_centers(Nr: int, p0: float = P0) -> np.ndarray:
    """Pressure at cell centres [Pa] for Nr uniform layers from 0 to p0."""
    delR = p0 / Nr
    return (np.arange(Nr) + 0.5) * delR


def write_data(
    path: Path,
    *,
    Nlon: int,
    Nlat: int,
    Nr: int,
    delta_t: float,
    n_iter0: int,
    n_timesteps: int,
    write_pickup: bool,
    pchkpt_freq: float,
    has_ic_file: bool,
    T0: float,
    delta_theta_z: float,
) -> None:
    """Write the main ``data`` namelist.

    Args:
        path:          Destination file path.
        Nlon:          Number of longitude points.
        Nlat:          Number of latitude points.
        Nr:            Number of vertical levels.
        delta_t:       Timestep [s].
        n_iter0:       Starting iteration (0 for spin-up, spinup_steps for data phase).
        n_timesteps:   Number of timesteps to run.
        write_pickup:  Whether to write a pickup file at the end.
        pchkpt_freq:   Permanent checkpoint frequency [s] (set to run duration for
                       end-of-run checkpoint only).
        has_ic_file:   If True, reference ``T.init.data`` as hydrogThetaFile.
        T0:            Reference surface temperature [K] for tRef profile.
        delta_theta_z: Surface-to-tropopause ΔΘ [K] for tRef profile.
    """
    del_lon = 360.0 / Nlon  # degrees
    del_lat = 180.0 / Nlat  # degrees
    del_r   = P0 / Nr       # Pa per layer (uniform)

    p_centers = _pressure_centers(Nr)
    t_ref = reference_temperature_profile(p_centers, T0=T0, delta_theta_z=delta_theta_z)
    t_ref_str = ",\n  ".join(_fmt_real(t) for t in t_ref)

    ic_line = (
        f"  hydrogThetaFile = 'T.init.data',\n"
        if has_ic_file else ""
    )
    content = f"""\
# MITgcm Held-Suarez atmospheric configuration
# Generated by datagen.mitgcm.namelist
 &PARM01
  tRef         = {t_ref_str},
  no_slip_sides  = .FALSE.,
  no_slip_bottom = .FALSE.,
  buoyancyRelation = 'ATMOSPHERIC',
  atm_Rd       = {_fmt_real(R_DRY)},
  atm_Cp       = {_fmt_real(CP)},
  atm_Po       = {_fmt_real(P0)},
  gravity      = 9.80616,
  rhoConst       = 1.0,
  useNHMTerms   = .FALSE.,
  useCoriolis   = .TRUE.,
  selectCoriScheme = 1,
  f0            = 0.0,
  beta          = 0.0,
  tempAdvScheme  = 33,
  staggerTimeStep = .TRUE.,
  implicitFreeSurface = .TRUE.,
  exactConserv   = .TRUE.,
  hFacMin        = 0.1,
  viscAh         = 0.0,
  diffKhT        = 0.0,
 /

 &PARM02
  cg2dMaxIters  = 200,
  cg2dTargetResidual = 1.0e-13,
 /

 &PARM03
  nIter0        = {n_iter0},
  nTimeSteps    = {n_timesteps},
  deltaTmom     = {_fmt_real(delta_t)},
  deltaTtracer  = {_fmt_real(delta_t)},
  deltaTClock   = {_fmt_real(delta_t)},
  abEps         = 0.1,
  forcing_In_AB  = .FALSE.,
  momDissip_In_AB= .FALSE.,
  pChkptFreq    = {_fmt_real(pchkpt_freq)},
  chkptFreq     = 0.0,
  writePickupAtEnd = {".TRUE." if write_pickup else ".FALSE."},
 /

 &PARM04
  usingSphericalPolarGrid = .TRUE.,
  delX         = {Nlon}*{_fmt_real(del_lon)},
  delY         = {Nlat}*{_fmt_real(del_lat)},
  delR         = {Nr}*{_fmt_real(del_r)},
  ygOrigin     = -90.0,
  xgOrigin     = 0.0,
  rSphere      = {_fmt_real(R_EARTH)},
 /

 &PARM05
{ic_line}\
 /
"""
    Path(path).write_text(content)


def write_data_pkg(path: Path, *, use_diagnostics: bool = True) -> None:
    """Write ``data.pkg`` — runtime package enable/disable flags."""
    diag_flag = ".TRUE." if use_diagnostics else ".FALSE."
    content = f"""\
 &PACKAGES
  useDiagnostics = {diag_flag},
  useShap_Filt   = .TRUE.,
 /
"""
    Path(path).write_text(content)


def write_eedata(path: Path) -> None:
    """Write MITgCM execution-environment settings."""
    content = """\
 &EEPARMS
  nTx = 1,
  nTy = 1,
 /
"""
    Path(path).write_text(content)


def write_data_hs_forc(
    path: Path,
    *,
    kf: float,
    ka: float,
    ks: float,
    delta_T_y: float,
    delta_theta_z: float,
    sigmab: float,
    T0: float,
) -> None:
    """Write ``data.hs_forc`` — Held-Suarez forcing parameters.

    The custom ``hs_forc_readparms.F`` in ``code/`` reads this file. All
    rates are in SI units (1/s); the Fortran code does not convert from days.

    Args:
        kf:            Rayleigh surface-drag rate [1/s].
        ka:            Free-atmosphere Newtonian cooling rate [1/s].
        ks:            Surface Newtonian cooling rate [1/s].
        delta_T_y:     Equator-to-pole temperature difference ΔTy [K].
        delta_theta_z: Surface-to-tropopause temperature difference Δθz [K].
        sigmab:        Boundary-layer top (normalised pressure).
        T0:            Reference surface temperature [K].
    """
    content = f"""\
 &HS_FORC_PARM01
  HS_kf         = {_fmt_real(kf)},
  HS_ka         = {_fmt_real(ka)},
  HS_ks         = {_fmt_real(ks)},
  HS_DeltaT_y   = {_fmt_real(delta_T_y)},
  HS_DeltaT_z   = {_fmt_real(delta_theta_z)},
  HS_sigmab     = {_fmt_real(sigmab)},
  HS_T0         = {_fmt_real(T0)},
 /
"""
    Path(path).write_text(content)


def write_data_diagnostics(
    path: Path,
    *,
    snapshot_interval_s: float,
    Nr: int = 20,
) -> None:
    """Write ``data.diagnostics`` — output field list and frequency.

    Outputs instantaneous snapshots (positive frequency) of:
      - UVEL  : zonal velocity [m/s]       — 3-D (Nr levels)
      - VVEL  : meridional velocity [m/s]  — 3-D
      - THETA : potential temperature [K]  — 3-D
      - ETAN  : surface pressure deviation [Pa] — 2-D (ETAN = ps − p0)

    The diagnostics package is only active in the data-collection phase; the
    spin-up phase writes ``data.pkg`` with ``useDiagnostics=.FALSE.``.

    Args:
        snapshot_interval_s: Output cadence in seconds (positive = snapshot).
    """
    levels = ", ".join(str(k) for k in range(1, Nr + 1))
    content = f"""\
 &DIAGNOSTICS_LIST
  dumpAtLast    = .TRUE.,
  diag_mnc      = .FALSE.,
  fields(1:3,1) = 'UVEL    ','VVEL    ','THETA   ',
  levels(1:{Nr},1) = {levels},
  fileName(1)   = 'atm_state',
  frequency(1)  = {_fmt_real(snapshot_interval_s)},
  timePhase(1)  = 0.,
  fields(1:1,2) = 'ETAN    ',
  fileName(2)   = 'atm_surf',
  frequency(2)  = {_fmt_real(snapshot_interval_s)},
  timePhase(2)  = 0.,
 /

 &DIAG_STATIS_PARMS
  stat_freq     = -1.,
 /
"""
    Path(path).write_text(content)


def write_data_shap(path: Path) -> None:
    """Write ``data.shap`` — Shapiro filter parameters.

    Fourth-order Shapiro filter (nShapUV=4 → 8th-order) damps grid-scale
    numerical noise in the momentum and tracer fields without an explicit
    viscosity. The timescale ``Shap_Trtau=1200s`` damps the smallest resolved
    scales (k=Nyquist) on a sub-timestep timescale.
    """
    content = """\
 &SHAP_PARM01
  Shap_funct    = 2,
  Shap_Trtau    = 1200.,
  Shap_uvtau    = 1200.,
  nShapT        = 4,
  nShapUV       = 4,
  nShapTrPhys   = 0,
  nShapUVPhys   = 0,
 /
"""
    Path(path).write_text(content)


def write_all_namelists(
    run_dir: Path,
    *,
    Nlon: int,
    Nlat: int,
    Nr: int,
    delta_t: float,
    n_iter0: int,
    n_timesteps: int,
    write_pickup: bool,
    pchkpt_freq: float,
    has_ic_file: bool,
    has_diagnostics: bool,
    snapshot_interval_s: float,
    kf: float,
    ka: float,
    ks: float,
    delta_T_y: float,
    delta_theta_z: float,
    sigmab: float,
    T0: float,
) -> None:
    """Write all namelist files for one MITgcm run phase into ``run_dir``."""
    run_dir = Path(run_dir)
    write_data(
        run_dir / "data",
        Nlon=Nlon, Nlat=Nlat, Nr=Nr,
        delta_t=delta_t,
        n_iter0=n_iter0,
        n_timesteps=n_timesteps,
        write_pickup=write_pickup,
        pchkpt_freq=pchkpt_freq,
        has_ic_file=has_ic_file,
        T0=T0,
        delta_theta_z=delta_theta_z,
    )
    write_data_pkg(run_dir / "data.pkg", use_diagnostics=has_diagnostics)
    write_eedata(run_dir / "eedata")
    write_data_hs_forc(
        run_dir / "data.hs_forc",
        kf=kf, ka=ka, ks=ks,
        delta_T_y=delta_T_y,
        delta_theta_z=delta_theta_z,
        sigmab=sigmab,
        T0=T0,
    )
    if has_diagnostics:
        write_data_diagnostics(
            run_dir / "data.diagnostics",
            snapshot_interval_s=snapshot_interval_s,
            Nr=Nr,
        )
    write_data_shap(run_dir / "data.shap")
