"""MITgcm Held-Suarez GCM solver: orchestrates compilation output → Zarr.

The ``run_simulation`` entry point follows the same interface as all other
datagen solvers (``params: dict``, ``out_dir: Path``, ``config``,
``**overrides``), but MITgcm is a compiled Fortran/C binary rather than a
Python library. The internal implementation therefore:

1. Sets up a working directory with namelists, IC files, and symlinks.
2. Runs MITgcm via ``subprocess`` in **two sequential phases**:
   - *Spin-up* (``spinup_days``, no diagnostic output) — lets the atmosphere
     develop realistic jets and eddies from the initial state.
   - *Data collection* (``data_days``, daily snapshots) — restarts from the
     spin-up pickup file and writes the output Zarr.
3. Reads the tiled MDS binary output and extracts fields at the configured
   pressure level plus surface pressure.
4. Writes a ``(time, field, lat, lon)`` float32 Zarr via
   ``datagen.resample.write_latlon_zarr``.

The two-phase design avoids wasting disk space on spin-up snapshots: the
data-collection phase only starts diagnostic output after the atmosphere
has reached statistical equilibrium.

Requires:
  - A compiled ``mitgcmuv`` executable (produced by ``scripts/build.py``).
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
import time
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any

import numpy as np

from datagen.mitgcm._constants import (
    HS_KA,
    HS_KF,
    HS_KS,
    HS_DELTA_T_Y,
    HS_DELTA_T_Z,
    HS_SIGMAB,
    HS_T0,
    P0,
)
from datagen.mitgcm.ic import write_bathymetry, write_temperature_ic
from datagen.mitgcm.namelist import write_all_namelists
from datagen.resample import write_latlon_zarr, regular_lat_grid, regular_lon_grid

logger = logging.getLogger(__name__)

# Default executable path — overridden by RunConfig.executable.
_DEFAULT_EXECUTABLE = Path(__file__).parent / "build" / "mitgcmuv"
# Default static-input directory (bathymetry, grid files) symlinked into each
# run dir. Sits next to build/, generated by datagen/mitgcm/scripts/build.py.
_DEFAULT_INPUT_DIR = Path(__file__).parent / "input"


# ─────────────────────────────────────────────────────────────────────────────
# Configuration dataclasses
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class RunConfig:
    """Numerical and infrastructure settings for one MITgcm run.

    Physical parameter choices (forcing timescales, temperature differences)
    live in ``SimulationParams`` and vary across the ensemble. Settings here
    are fixed for a given compiled binary and hardware configuration.

    Attributes:
        Nlon:          Number of longitude grid points (must match SIZE.h).
        Nlat:          Number of latitude grid points (must match SIZE.h).
        Nr:            Number of vertical pressure levels (must match SIZE.h).
        n_mpi:         Number of MPI ranks to launch (must be consistent with
                       nPy × nPx × nSx × nSy in SIZE.h; default 4 = nPy=4).
        delta_t:       Timestep [s]. Must satisfy CFL for the given resolution.
        spinup_days:   Spin-up duration [days] — run without output.
        data_days:     Data-collection duration [days] — daily snapshots saved.
        snapshot_interval_days: Output cadence [days].
        pressure_hpa:  Pressure level [hPa] to extract for u, v, T output.
        executable:    Path to the compiled ``mitgcmuv`` binary.
        input_dir:     Directory of static input files (bathymetry, grid)
                       symlinked into every run dir. Defaults to ``input/``
                       beside the executable's package, generated by build.py.
        mpirun_cmd:    MPI launcher command (list of strings prepended to the
                       executable invocation; set to ``[]`` for serial runs).
        timeout_factor: Wall-clock timeout = ``total_sim_seconds × factor``.
    """
    # Grid — must match SIZE.h compile-time constants.
    Nlon: int = 128
    Nlat: int = 64
    Nr: int = 20
    n_mpi: int = 4

    # Time.
    delta_t: float = 600.0
    spinup_days: float = 200.0
    data_days: float = 365.0
    snapshot_interval_days: float = 1.0

    # Output.
    pressure_hpa: float = 500.0

    # Infrastructure.
    executable: Path = field(default_factory=lambda: _DEFAULT_EXECUTABLE)
    input_dir: Path = field(default_factory=lambda: _DEFAULT_INPUT_DIR)
    mpirun_cmd: tuple[str, ...] = ("mpirun", "-n", "{n_mpi}")
    timeout_factor: float = 3.0

    # ── Derived quantities ────────────────────────────────────────────────────
    @property
    def spinup_seconds(self) -> float:
        return self.spinup_days * 86400.0

    @property
    def data_seconds(self) -> float:
        return self.data_days * 86400.0

    @property
    def snapshot_interval_s(self) -> float:
        return self.snapshot_interval_days * 86400.0

    @property
    def spinup_steps(self) -> int:
        return round(self.spinup_seconds / self.delta_t)

    @property
    def data_steps(self) -> int:
        return round(self.data_seconds / self.delta_t)

    @property
    def timeout_s(self) -> float:
        return (self.spinup_seconds + self.data_seconds) * self.timeout_factor


@dataclass(frozen=True)
class SimulationParams:
    """Physical parameters of one Held-Suarez ensemble member.

    All forcing timescales are stored internally as rates [1/s] to match the
    Fortran namelist convention.  The ``from_dict`` constructor accepts the
    natural user-facing representation (timescales in days).
    """
    kf: float            # Rayleigh surface-drag rate [1/s]
    ka: float            # Free-atmosphere Newtonian cooling rate [1/s]
    ks: float            # Surface Newtonian cooling rate [1/s]
    delta_T_y: float     # Equator-to-pole temperature difference [K]
    delta_theta_z: float # Surface-to-tropopause temperature difference [K]
    seed: int            # RNG seed for IC perturbation

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "SimulationParams":
        """Build from a JSON param dict (timescales in days, ΔT in K)."""
        return cls(
            kf=1.0 / (float(d["tau_drag_days"]) * 86400.0),
            ka=1.0 / (float(d.get("tau_atm_days", 40.0)) * 86400.0),
            ks=1.0 / (float(d["tau_surf_days"]) * 86400.0),
            delta_T_y=float(d["delta_T_y"]),
            delta_theta_z=float(d["delta_theta_z"]),
            seed=int(d["seed"]),
        )


# ─────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────────────────────

def _build_mpirun_cmd(cfg: RunConfig) -> list[str]:
    """Expand ``{n_mpi}`` placeholder in the mpirun command template."""
    return [
        tok.format(n_mpi=cfg.n_mpi) for tok in cfg.mpirun_cmd
    ]


def _symlink_inputs(run_dir: Path, input_dir: Path | None) -> None:
    """Symlink every file in ``input_dir`` into ``run_dir``.

    The shared ``input/`` directory contains static files that are identical
    across all runs (bathymetry, grid files, etc.). We symlink rather than copy
    to avoid duplicating potentially large binary files.
    """
    if input_dir is None:
        return
    input_dir = Path(input_dir)
    if not input_dir.is_dir():
        logger.warning("input_dir %s does not exist — skipping symlinks", input_dir)
        return
    for src in input_dir.iterdir():
        dst = run_dir / src.name
        if not dst.exists():
            dst.symlink_to(src.resolve())


def _setup_run_dir(
    run_dir: Path,
    cfg: RunConfig,
    sim_params: SimulationParams,
    *,
    phase: int,           # 1 = spin-up, 2 = data collection
    executable: Path,
    input_dir: Path | None,
) -> None:
    """Populate ``run_dir`` with the executable symlink, IC files, and namelists."""
    run_dir.mkdir(parents=True, exist_ok=True)

    # Symlink the compiled executable.
    exe_link = run_dir / "mitgcmuv"
    if not exe_link.exists():
        exe_link.symlink_to(Path(executable).resolve())

    # Symlink static inputs (grid coord files, etc.).
    _symlink_inputs(run_dir, input_dir)

    if phase == 1:
        # Write IC files only for the spin-up phase.
        write_temperature_ic(
            run_dir / "T.init.data",
            Nlon=cfg.Nlon, Nlat=cfg.Nlat, Nr=cfg.Nr,
            seed=sim_params.seed,
        )
        write_bathymetry(
            run_dir / "bathyFile.bin",
            Nlon=cfg.Nlon, Nlat=cfg.Nlat,
        )

    is_spinup = (phase == 1)
    write_all_namelists(
        run_dir,
        Nlon=cfg.Nlon, Nlat=cfg.Nlat, Nr=cfg.Nr,
        delta_t=cfg.delta_t,
        n_iter0=0 if is_spinup else cfg.spinup_steps,
        n_timesteps=cfg.spinup_steps if is_spinup else cfg.data_steps,
        write_pickup=is_spinup,
        # Write pickup only at end of spin-up.
        pchkpt_freq=cfg.spinup_seconds if is_spinup else 0.0,
        has_ic_file=is_spinup,
        has_diagnostics=not is_spinup,
        snapshot_interval_s=cfg.snapshot_interval_s,
        kf=sim_params.kf,
        ka=sim_params.ka,
        ks=sim_params.ks,
        delta_T_y=sim_params.delta_T_y,
        delta_theta_z=sim_params.delta_theta_z,
        sigmab=HS_SIGMAB,
        T0=HS_T0,
    )


def _launch_mitgcm(
    run_dir: Path,
    cfg: RunConfig,
    *,
    phase: int,
) -> None:
    """Run ``mitgcmuv`` in ``run_dir`` and stream its stdout to a log file.

    Raises:
        RuntimeError: If the process exits with a non-zero return code.
    """
    cmd = _build_mpirun_cmd(cfg) + ["./mitgcmuv"]
    log_path = run_dir / f"STDOUT_phase{phase}.log"
    for pattern in ("STDOUT.????", "STDERR.????"):
        for old_log in run_dir.glob(pattern):
            old_log.unlink()
    t0 = time.time()
    logger.info("Phase %d: launching %s (cwd=%s)", phase, cmd, run_dir)
    with open(log_path, "w") as log_f:
        result = subprocess.run(
            cmd,
            cwd=run_dir,
            stdout=log_f,
            stderr=subprocess.STDOUT,
            timeout=cfg.timeout_s,
        )
    elapsed = time.time() - t0
    logger.info("Phase %d finished in %.1f s (exit=%d)", phase, elapsed, result.returncode)
    if result.returncode != 0:
        raise RuntimeError(
            f"MITgcm phase {phase} exited with code {result.returncode}. "
            f"See {log_path}"
        )
    fatal_lines: list[str] = []
    for rank_log in sorted(run_dir.glob("STDERR.????")):
        text = rank_log.read_text(errors="replace")
        for line in text.splitlines():
            if "*** ERROR ***" in line or "ABNORMAL END" in line:
                fatal_lines.append(f"{rank_log.name}: {line}")
                break
    for rank_log in sorted(run_dir.glob("STDOUT.????")):
        text = rank_log.read_text(errors="replace")
        for line in text.splitlines():
            if "PROGRAM MAIN: ends with fatal Error" in line:
                fatal_lines.append(f"{rank_log.name}: {line}")
                break
    if fatal_lines:
        detail = "\n".join(fatal_lines[:8])
        raise RuntimeError(
            f"MITgcm phase {phase} reported fatal errors despite exit code 0. "
            f"See {log_path} and rank logs in {run_dir}.\n{detail}"
        )


def _find_diag_iters(run_dir: Path) -> list[int]:
    """Return sorted list of iteration numbers from ``atm_state.*.meta`` files."""
    meta_files = sorted(run_dir.glob("atm_state.*.meta"))
    iters = []
    for p in meta_files:
        # Tiled filename: atm_state.0000086400.001.001.meta -> 86400
        # Global filename: atm_state.0000086400.meta -> 86400
        stem = p.stem
        parts = stem.split(".")
        if len(parts) >= 2:
            try:
                iters.append(int(parts[1]))
            except ValueError:
                continue
    return sorted(set(iters))


def _parse_mds_meta(path: Path) -> dict[str, Any]:
    """Parse the small subset of MITgCM MDS metadata used by diagnostics."""
    text = path.read_text()

    def _int_value(name: str) -> int:
        match = re.search(rf"{name}\s*=\s*\[\s*([0-9]+)\s*\]", text)
        if match is None:
            raise ValueError(f"{path}: missing {name}")
        return int(match.group(1))

    dim_match = re.search(r"dimList\s*=\s*\[(.*?)\];", text, re.S)
    if dim_match is None:
        raise ValueError(f"{path}: missing dimList")
    dim_nums = [int(v) for v in re.findall(r"[-+]?\d+", dim_match.group(1))]
    if len(dim_nums) % 3 != 0:
        raise ValueError(f"{path}: malformed dimList")
    dim_list = [
        (dim_nums[i], dim_nums[i + 1], dim_nums[i + 2])
        for i in range(0, len(dim_nums), 3)
    ]

    fields_match = re.search(r"fldList\s*=\s*\{(.*?)\};", text, re.S)
    fields = []
    if fields_match is not None:
        fields = [
            field.strip()
            for field in re.findall(r"'([^']+)'", fields_match.group(1))
        ]

    prec_match = re.search(r"dataprec\s*=\s*\[\s*'([^']+)'\s*\]", text)
    dataprec = prec_match.group(1).strip() if prec_match else "float32"

    return {
        "n_dims": _int_value("nDims"),
        "dim_list": dim_list,
        "dataprec": dataprec,
        "nrecords": _int_value("nrecords"),
        "time_step": _int_value("timeStepNumber"),
        "fields": fields,
    }


def _mds_dtype(dataprec: str) -> np.dtype:
    """Return the big-endian NumPy dtype for an MDS ``dataprec`` value."""
    if dataprec == "float32":
        return np.dtype(">f4")
    if dataprec == "float64":
        return np.dtype(">f8")
    raise ValueError(f"Unsupported MDS dataprec: {dataprec}")


def _read_mds_prefix(
    run_dir: Path,
    prefix: str,
    iters: list[int],
) -> dict[str, np.ndarray]:
    """Read a tiled MITgCM diagnostics prefix into field arrays."""
    fields: dict[str, np.ndarray] = {}

    for t_idx, iter_num in enumerate(iters):
        tile_metas = sorted(run_dir.glob(f"{prefix}.{iter_num:010d}.*.*.meta"))
        if not tile_metas:
            global_meta = run_dir / f"{prefix}.{iter_num:010d}.meta"
            tile_metas = [global_meta] if global_meta.exists() else []
        if not tile_metas:
            raise FileNotFoundError(f"No {prefix}.{iter_num:010d}.*.meta files found")

        for meta_path in tile_metas:
            meta = _parse_mds_meta(meta_path)
            dim_list = meta["dim_list"]
            nx_g, x_start, x_end = dim_list[0]
            ny_g, y_start, y_end = dim_list[1]
            nx = x_end - x_start + 1
            ny = y_end - y_start + 1
            data_path = meta_path.with_suffix(".data")
            raw = np.fromfile(data_path, dtype=_mds_dtype(meta["dataprec"]))
            raw = raw.astype(np.float32, copy=False)

            if meta["n_dims"] == 3:
                nz_g, z_start, z_end = dim_list[2]
                nz = z_end - z_start + 1
                expected = meta["nrecords"] * nz * ny * nx
                if raw.size != expected:
                    raise ValueError(
                        f"{data_path}: expected {expected} values, found {raw.size}"
                    )
                tile = raw.reshape((meta["nrecords"], nz, ny, nx))
                for rec_idx, field_name in enumerate(meta["fields"]):
                    arr = fields.setdefault(
                        field_name,
                        np.empty((len(iters), nz_g, ny_g, nx_g), dtype=np.float32),
                    )
                    arr[
                        t_idx,
                        z_start - 1:z_end,
                        y_start - 1:y_end,
                        x_start - 1:x_end,
                    ] = tile[rec_idx]
            elif meta["n_dims"] == 2:
                expected = meta["nrecords"] * ny * nx
                if raw.size != expected:
                    raise ValueError(
                        f"{data_path}: expected {expected} values, found {raw.size}"
                    )
                tile = raw.reshape((meta["nrecords"], ny, nx))
                for rec_idx, field_name in enumerate(meta["fields"]):
                    arr = fields.setdefault(
                        field_name,
                        np.empty((len(iters), ny_g, nx_g), dtype=np.float32),
                    )
                    arr[t_idx, y_start - 1:y_end, x_start - 1:x_end] = tile[rec_idx]
            else:
                raise ValueError(f"{meta_path}: unsupported nDims={meta['n_dims']}")

    return fields


def _read_mitgcm_output(run_dir: Path, cfg: RunConfig) -> dict[str, np.ndarray]:
    """Read the MITgCM diagnostics needed for benchmark Zarr output."""

    iters = _find_diag_iters(run_dir)
    if not iters:
        raise FileNotFoundError(
            f"No atm_state.*.meta files found in {run_dir}. "
            "Did the data-collection phase produce output?"
        )

    data = _read_mds_prefix(run_dir, "atm_state", iters)
    data.update(_read_mds_prefix(run_dir, "atm_surf", iters))
    data["pressure"] = (
        (np.arange(cfg.Nr, dtype=np.float32) + 0.5) * (P0 / cfg.Nr)
    )
    data["time"] = np.asarray(iters, dtype=np.float64) * cfg.delta_t
    return data


def _extract_fields(
    data: dict[str, np.ndarray],
    cfg: RunConfig,
) -> tuple[list[np.ndarray], list[str], np.ndarray]:
    """Extract 2-D fields from the MITgCM diagnostic arrays.

    Returns:
        field_arrays: List of (Nt, Nlat, Nlon) float32 arrays.
        field_names:  Corresponding field name strings.
        time_arr:     Time coordinate in seconds since data-collection start.
    """
    # Pressure at model-level centres in Pa.
    p_target = cfg.pressure_hpa * 100.0  # hPa -> Pa
    z_vals = data["pressure"]
    k_idx = int(np.argmin(np.abs(z_vals - p_target)))
    p_actual_hpa = z_vals[k_idx] / 100.0
    logger.info(
        "Extracting pressure level %.0f hPa (nearest: %.1f hPa, index k=%d)",
        cfg.pressure_hpa, p_actual_hpa, k_idx,
    )

    u  = data["UVEL"][:, k_idx, :, :].astype(np.float32)
    v  = data["VVEL"][:, k_idx, :, :].astype(np.float32)
    T  = data["THETA"][:, k_idx, :, :].astype(np.float32)
    ps = (data["ETAN"] + P0).astype(np.float32)  # ETAN = ps - p0

    pressure_label = f"{cfg.pressure_hpa:.0f}hpa"
    field_arrays = [u, v, T, ps]
    field_names  = [
        f"u_{pressure_label}",
        f"v_{pressure_label}",
        f"T_{pressure_label}",
        "ps",
    ]

    # Iteration timestamps include restart offset; rebase to collection start.
    time_s = data["time"].astype(np.float64)
    time_arr = time_s - time_s[0]

    return field_arrays, field_names, time_arr


def _write_zarr(
    ds,
    out_path: Path,
    cfg: RunConfig,
    params: dict,
) -> None:
    """Extract pressure-level fields and write the benchmark Zarr store."""
    field_arrays, field_names, time_arr = _extract_fields(ds, cfg)

    lat_target = regular_lat_grid(cfg.Nlat)
    lon_target = regular_lon_grid(cfg.Nlon)

    write_latlon_zarr(
        out_path,
        time_arr=time_arr,
        field_arrays=field_arrays,
        field_names=field_names,
        lat_target=lat_target,
        lon_target=lon_target,
        description=(
            f"MITgcm Held-Suarez GCM, sphericalpolar {cfg.Nlon}×{cfg.Nlat}×{cfg.Nr}, "
            f"fields at {cfg.pressure_hpa:.0f} hPa + surface pressure."
        ),
        run_id=None,
        params=params,
    )
    logger.info("Wrote Zarr store to %s", out_path)


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

def run_simulation(
    params: dict[str, Any],
    out_dir: Path,
    config: RunConfig | None = None,
    **overrides: Any,
) -> None:
    """Run one MITgcm Held-Suarez simulation and write a benchmark Zarr.

    Implements the two-phase strategy: spin-up (no output) followed by data
    collection (daily snapshots). Both phases share the same ``run_dir``; the
    spin-up leaves a pickup file that the data phase restarts from.

    Args:
        params:   Physical parameter dict from ``generate_sweep.py``.  Keys:
                  ``tau_drag_days``, ``tau_surf_days``, ``delta_T_y``,
                  ``delta_theta_z``, ``seed``.  ``tau_atm_days`` defaults to 40.
        out_dir:  Root output directory.  The MITgcm working directory is
                  created as ``out_dir/mitgcm_run/``; the final Zarr is at
                  ``out_dir/run.zarr``.
        config:   Numerical / infrastructure configuration.  Defaults to
                  ``RunConfig()`` if ``None``.
        **overrides: Per-call overrides for individual ``RunConfig`` fields.

    Raises:
        RuntimeError: If the MITgcm executable returns a non-zero exit code.
        FileNotFoundError: If the compiled executable does not exist.
        ImportError: If ``xmitgcm`` is not installed.
    """
    base = config if config is not None else RunConfig()
    cfg = replace(base, **overrides) if overrides else base

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    run_dir = out_dir / "mitgcm_run"

    executable = Path(cfg.executable)
    if not executable.exists():
        raise FileNotFoundError(
            f"MITgcm executable not found: {executable}. "
            "Run datagen/mitgcm/scripts/build.py first."
        )

    input_dir = Path(cfg.input_dir)
    sim_params = SimulationParams.from_dict(params)

    logger.info(
        "Starting MITgcm run: τ_drag=%.1f d  τ_surf=%.1f d  "
        "ΔTy=%.1f K  Δθz=%.1f K  seed=%d",
        1.0 / (sim_params.kf * 86400.0),
        1.0 / (sim_params.ks * 86400.0),
        sim_params.delta_T_y,
        sim_params.delta_theta_z,
        sim_params.seed,
    )

    # ── Phase 1: spin-up ─────────────────────────────────────────────────────
    logger.info("Phase 1: spin-up (%.0f days, no output)", cfg.spinup_days)
    _setup_run_dir(run_dir, cfg, sim_params, phase=1,
                   executable=executable, input_dir=input_dir)
    _launch_mitgcm(run_dir, cfg, phase=1)

    # ── Phase 2: data collection ──────────────────────────────────────────────
    logger.info("Phase 2: data collection (%.0f days, daily snapshots)", cfg.data_days)
    _setup_run_dir(run_dir, cfg, sim_params, phase=2,
                   executable=executable, input_dir=input_dir)
    _launch_mitgcm(run_dir, cfg, phase=2)

    # ── Read output and write Zarr ────────────────────────────────────────────
    logger.info("Reading MDS output and writing Zarr")
    ds = _read_mitgcm_output(run_dir, cfg)
    _write_zarr(ds, out_dir / "run.zarr", cfg, params)
